name:多仓库镜像任务
on:
  workflow_dispatch: #网页手动点按钮执行
  schedule:
    - cron: '0 */6 * * *' #每6小时自动同步

jobs:
  gitee_sync:
    runs-on: ubuntu‑latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch‑depth:0

      - name: GitHub同步Gitee
        uses: ./ #重点！./代表使用本仓库（fork后的hub‑mirror‑action）本地action代码
        with:
          src: github/lau‑yeung
          dst: gitee/lauyeung
          static_list: "SkillsV3.1,repo2,repo3"
          clone_style: ssh
          src_token: ${{ secrets.SRC_GITHUB_API_TOKEN }}
          dst_key: ${{ secrets.HUB_MIRROR_SSH_PRIVATE_KEY }}
          force_update: true
          debug: true

  gitlab_sync:
    runs‑on: ubuntu‑latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch‑depth:0

      - name: GitHub同步GitLab
        uses: ./
        with:
          src: github/lau‑yeung
          dst: gitlab/lau_yeung
          static_list: "SkillsV3.1,repo2,repo3"
          clone_style: ssh
          src_token: ${{ secrets.SRC_GITHUB_API_TOKEN }}
          dst_key: ${{ secrets.HUB_MIRROR_SSH_PRIVATE_KEY }}
          force_update: true
          debug: true
